--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.53.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25.09.2017 12:58:00
-- Server version: 5.5.56
-- Client version: 4.1
--


--
-- Definition for database mobile
--
DROP DATABASE IF EXISTS mobile;
CREATE DATABASE mobile
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE mobile;

--
-- Definition for table balance
--
CREATE TABLE balance (
  id INT(11) NOT NULL AUTO_INCREMENT,
  client_id VARCHAR(255) NOT NULL,
  phone_number VARCHAR(10) NOT NULL,
  balance DOUBLE(7, 2) DEFAULT 0.00,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table clients
--
CREATE TABLE clients (
  id INT(11) NOT NULL AUTO_INCREMENT,
  login VARCHAR(10) NOT NULL,
  password VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table balance
--

-- Table mobile.balance does not contain any data (it is empty)

-- 
-- Dumping data for table clients
--

-- Table mobile.clients does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;